# Generated by Django 6.1.1 on 2026-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='part',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP'),
        ),
    ]
