# Generated by Django 6.1.1 on 2026-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_part_discount_part_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter discount percentage, e.g. 10 for 10% OFF', max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling Price'),
        ),
    ]
